#!/bin/bash
GPG_KEYID=${DIARY_KEYID:-"83BB96DF"}
EDITOR=${DIARY_EDITOR:-"vi"}

[[ -n "$1" ]] || (echo "file not found!"; exit 1)
tmp=$(mktemp -t diary)
# save every draft
fswatch -0 "$tmp" | xargs -0 -n 1 -I {} gpg --output "$1.tmp" --encrypt --armor --recipient "$GPG_KEYID" --yes --quiet "$tmp"  &
FSWATCH_PID=$!

# decrypt, edit, encrypt
gpg --decrypt --output "$tmp" --yes --quiet "$1" && \
$EDITOR "$tmp"
gpg --output "$1" --encrypt --armor --recipient "$GPG_KEYID" --yes --quiet "$tmp"

# cleanup
kill $FSWATCH_PID
rm "$tmp"
