#!/bin/bash 
GPG_KEYID=83BB96DF
ENTRIES_DIR=~/diary
file="$ENTRIES_DIR/$(date  +%Y-%m-%d_%H%M%S).txt.asc"
cat | gpg --output $file --encrypt --armor --recipient "$GPG_KEYID" --yes --quiet -
ls -la $file