#!/bin/bash 
ENTRIES_DIR=${DIARY_DIRECTORY:-"~/diary"}
GPG_CMD=${DIARY_GPG:-"gpg2"}
READER=${DIARY_READER:-"less"}
(
for file in ~/diary/*; do
	echo "---------------- $(basename $file .asc) ------------"
	$GPG_CMD --decrypt --output "-" --yes --quiet $file 2> /dev/null
	echo ""
done
) | $READER