#!/bin/bash 
GPG_KEYID=${DIARY_KEYID:-"83BB96DF"}
ENTRIES_DIR=${DIARY_DIRECTORY:-"~/diary"}

if [ $# -gt 0 ]; then 
    for file in $@; do
       dest="$ENTRIES_DIR/$(date  +%Y-%m-%d_%H%M%S).${file##*.}.asc"
       gpg --output $dest --encrypt --armor --recipient "$GPG_KEYID" --yes --quiet $file
       ls -la $dest
    done
else  
    dest="$ENTRIES_DIR/$(date  +%Y-%m-%d_%H%M%S).txt.asc"
    cat | gpg --output $dest --encrypt --armor --recipient "$GPG_KEYID" --yes --quiet -
    ls -la $dest
fi
